services:
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3-fpm
    container_name: wordpress_app
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

  composer:
    image: composer:latest
    container_name: wordpress_composer
    working_dir: /app
    volumes:
      - ./:/app
    command: ["composer", "install"]
    profiles: ["tools"]

volumes:
  db_data:
  wordpress_data:
